name: Zip and upload resource pack as an artifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up zip utility
      run: sudo apt-get install -y zip unzip

    - name: Zip each texture pack
      run: |
        cd $GITHUB_WORKSPACE
        # Parcourir chaque dossier de catégorie à la racine
        for category in */; do
          cd "$category"
          # Parcourir chaque sous-dossier (qui est un pack de textures)
          for texture_pack in */; do
            cd "$texture_pack"
            # Zipper le contenu du pack de textures directement
            zip -r "${category%/}/${texture_pack%/}.zip" ./*
            cd ..
            # Supprimer le dossier du pack de textures après zippage
            rm -rf "$texture_pack"
          done
          cd ..
        done

    - name: Zip the entire structure
      run: |
        cd $GITHUB_WORKSPACE
        # Zipper le dossier Crosshairs Collection avec pack.mcmeta au même niveau
        zip -r "Crosshairs Collection.zip" "Crosshairs Collection" pack.mcmeta

    - name: Upload the .zip as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: Extract this to get the resource pack
        path: "Crosshairs Collection.zip"
